gui:
  theme:
    selectedLineBgColor:
      - default
      - reverse
  border: rounded
  showBottomLine: false

git:
  log:
    showGraph: 'always'
  paging:
    colorArg: always
    pager: diff-so-fancy
  branchLogCmd: git log --all --decorate --oneline --graph

customCommands:
  - key: 'G'
    command: "git reset --hard {{.Form.Ref}}"
    context: localBranches
    prompts:
      - type: 'menuFromCommand'
        title: "Branch:"
        key: 'Ref'
        command: 'git branch -a --format="%(refname)"'
        filter: 'refs/(heads|remotes)/(.*)'
        valueFormat: '{{ .group_2 }}'
