#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/mattly/dotfiles/master/install/mac_bootstrap)"

ssh-keygen -t rsa
echo "Please upload your new SSH key to Github before continuing. It's on the clipboard"
cat ~/.ssh/id_rsa.pub | pbcopy
read -p "press return to continue"

brew install git

mkdir $HOME/projects
git clone git@github.com:mattly/dotfiles $HOME/projects/dotfiles
./symlink_configs

brew install fish
sudo tee -a /etc/shells /opt/homebrew/bin/fish
chsh -s /opt/homebrew/bin/fish
curl -L https://get.oh-my.fish | fish
omf install

