#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

ssh-keygen -t rsa
echo "Please upload your new SSH key to Github before continuing. It's on the clipboard"
cat ~/.ssh/id_rsa.pub | pbcopy
read -p "press return to continue"

brew install git

mkdir $HOME/projects
git clone git@github.com:mattly/dotfiles $HOME/projects/dotfiles
./symlink_configs
git clone https://github.com/hlissner/doom-emacs .emacs.d
defaults write org.gnu.Emacs NSAppSleepDisabled bool YES

brew install fish
sudo tee -a /etc/shells /usr/local/bin/fish
chsh -s /usr/local/bin/fish
curl -L https://get.oh-my.fish | fish
omf install

