include _init_mac.sh
include _basic_mac.sh
include _mac_main.sh
include _mac_fonts.sh
include _mac_dev_basics.sh
include _mac_dev_node.sh
include _mac_image.sh
include _mac_audio.sh
include _mac_settings.sh
